### ISSUE TITLE
Add dependencies as Meteor packages

### ISSUE THREAD

**Issue by Urigo** [planet-training/meteor-angular-material#2]
It's better to add the dependencies with Meteor packages:
- angular
- angular-animate
- angular-aria

also you can remove the dependency on angular-meteor because it's actually depends on angular and not on angular-meteor (theoretically)

**Comment by dohomi** [comment]
Hi @Urigo 
I found `angularjs:angular`and `angularjs:angular-animate`but not `angular-aria`yet. Do you know if there is any effort yet doing this?

**Comment by Urigo** [comment]
there is none and you be be that one :)
I already added you as part of the angularjs organization

**Comment by Urigo** [comment]
now there are and you can use them with the new 0.9.3

**Comment by dohomi** [comment]
Released with 0.9.3-rc3
