### ISSUE TITLE
Update angular:angular-material to 1.0.0!

### ISSUE THREAD

**Issue by MileanCo** [planet-training/meteor-angular-material#4]
Please update the angular:angular-material meteor package to the latest Material version; 1.0.0 rc 4

Link: https://atmospherejs.com/angular/angular-material
It's still 0.11 there.

**Comment by dohomi** [comment]
Hi @Mystec the version is up to date:
https://github.com/planet-training/meteor-angular-material/blob/master/bower.json
you need to add the `@1.0.0-rc4`into your packages file otherwise it takes the last stable built.

**Comment by MileanCo** [comment]
Thanks! That fixed the issue. 
I changed the line in .meteor/versions to say "angular:angular-material@1.0.0-rc4" instead of "@0.11.4". I figured "meteor update" would take care of this; apparently not.
